#define _CRT_SECURE_NO_WARNINGS
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <blst.h>

static FILE* outf(const char* path)
{
    if (!path || path[0] == '\0')
        return stdout;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "failed to open output file '%s'\n", path);
        return NULL;
    }
    return f;
}

int main(int argc, char** argv)
{
    const char* out_path = (argc > 1) ? argv[1] : NULL;
    FILE* f = outf(out_path);
    if (!f)
        return 2;

    fprintf(f, "// generated by blst_abi_probe.c - do not edit\n");
    fprintf(f, "#pragma once\n\n");
    fprintf(f, "#include <cstddef>\n\n");
    fprintf(f, "namespace Honey::Crypto::bls::abi {\n\n");

    fprintf(f, "inline constexpr std::size_t blst_p1_size = %zu;\n",
        (size_t)sizeof(blst_p1));
    fprintf(f, "inline constexpr std::size_t blst_p1_align = %zu;\n",
        (size_t)_Alignof(blst_p1));
    fprintf(f, "inline constexpr std::size_t blst_p1_affine_size = %zu;\n",
        (size_t)sizeof(blst_p1_affine));
    fprintf(f, "inline constexpr std::size_t blst_p1_affine_align = %zu;\n",
        (size_t)_Alignof(blst_p1_affine));

    fprintf(f, "inline constexpr std::size_t blst_p2_size = %zu;\n",
        (size_t)sizeof(blst_p2));
    fprintf(f, "inline constexpr std::size_t blst_p2_align = %zu;\n",
        (size_t)_Alignof(blst_p2));
    fprintf(f, "inline constexpr std::size_t blst_p2_affine_size = %zu;\n",
        (size_t)sizeof(blst_p2_affine));
    fprintf(f, "inline constexpr std::size_t blst_p2_affine_align = %zu;\n",
        (size_t)_Alignof(blst_p2_affine));

    fprintf(f, "inline constexpr std::size_t blst_scalar_size = %zu;\n",
        (size_t)sizeof(blst_scalar));
    fprintf(f, "inline constexpr std::size_t blst_scalar_align = %zu;\n",
        (size_t)_Alignof(blst_scalar));

    fprintf(f, "inline constexpr std::size_t blst_fp12_size = %zu;\n",
        (size_t)sizeof(blst_fp12));
    fprintf(f, "inline constexpr std::size_t blst_fp12_align = %zu;\n",
        (size_t)_Alignof(blst_fp12));

    fprintf(f,
        "inline constexpr std::size_t blst_scalar_serialized_size = 32;\n");

    fprintf(f, "inline constexpr std::size_t blst_p1_serialized_size = 96;\n");
    fprintf(f, "inline constexpr std::size_t blst_p1_compressed_size = 48;\n");

    fprintf(f, "inline constexpr std::size_t blst_p2_serialized_size = 192;\n");
    fprintf(f, "inline constexpr std::size_t blst_p2_compressed_size = 96;\n");

    fprintf(f, "\n} // namespace Honey::Crypto::bls::abi\n");

    if (f != stdout)
        fclose(f);
    return 0;
}
