target-version = "py314"
line-length = 100

exclude = [".venv", "native/rust", "**/__pycache__"]

[lint]
select = ["E", "F", "W", "I", "B", "UP"]
ignore = ["E501"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
