from typing import Any, List

"""
Type stubs for honey_native Rust module.
Provides threshold signatures, threshold public key encryption, AES helpers,
and Merkle-tree helpers.
"""


class SigPublicKey:
    @property
    def players(self) -> int: ...
    @property
    def threshold(self) -> int: ...
    def verify_share(self, player_id: int, sig_bytes: bytes, msg: bytes) -> bool: ...
    def combine_shares(self, shares: list[tuple[int, bytes]], msg: bytes) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "SigPublicKey": ...


class SigPrivateShare:
    @property
    def player_id(self) -> int: ...
    def sign(self, msg: bytes) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "SigPrivateShare": ...


class PkePublicKey:
    @property
    def players(self) -> int: ...
    @property
    def threshold(self) -> int: ...
    def encrypt(self, msg: bytes) -> bytes: ...
    def verify_ciphertext(self, ct_bin: bytes) -> bool: ...
    def verify_share(self, player_id: int, ct_bin: bytes, share_bin: bytes) -> bool: ...
    def combine_shares(self, ct_bin: bytes, shares_bin: list[bytes]) -> bytes: ...
    def master_public_key_bytes(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "PkePublicKey": ...


class PkePrivateShare:
    @property
    def player_id(self) -> int: ...
    def decrypt_share(self, ct_bin: bytes) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "PkePrivateShare": ...


def sig_generate(players: int, threshold: int) -> tuple[SigPublicKey, list[SigPrivateShare]]: ...
def pke_generate(players: int, threshold: int) -> tuple[PkePublicKey, list[PkePrivateShare]]: ...
def ecdsa_generate_keys(players: int) -> tuple[list[bytes], list[bytes]]: ...
def ecdsa_public_key_from_private(priv_key: bytes) -> bytes: ...
def ecdsa_sign(priv_key: bytes, msg: bytes) -> bytes: ...
def ecdsa_verify(pub_key: bytes, msg: bytes, sig_bytes: bytes) -> bool: ...
def ecdsa_verify_threshold_sigs(
    pub_keys: list[bytes], digest: bytes, sigmas: list[tuple[int, bytes]], threshold: int
) -> bool: ...

def aes_encrypt(key: bytes, plaintext: bytes) -> bytes: ...
def aes_decrypt(key: bytes, ciphertext: bytes) -> bytes: ...

def save_sig_keys(output_dir: str, params_bin: bytes, shares_bin: list[bytes]) -> None: ...
def save_pke_keys(
    output_dir: str, params_bin: bytes, mpk_bin: bytes, shares_bin: list[bytes]
) -> None: ...
def load_sig_keys(key_dir: str) -> tuple[bytes, list[bytes]]: ...
def load_pke_keys(key_dir: str) -> tuple[bytes, bytes, list[bytes]]: ...

def encode_encrypted_batch(encrypted_key: bytes, ciphertext: bytes) -> bytes: ...
def decode_encrypted_batch(payload: bytes) -> tuple[bytes, bytes]: ...
def encode_encrypted_batch_py(batch: Any) -> bytes: ...
def decode_encrypted_batch_py(payload: bytes) -> Any: ...
def encode_protocol_envelope(
    sender: int,
    round_id: int,
    channel: str,
    instance_id: int | None,
    message_type: str,
    byte_fields: list[bytes | None],
    int_fields: list[int],
) -> bytes: ...
def encode_protocol_envelope_py(sender: int, envelope: Any) -> bytes: ...
def decode_protocol_envelope(
    payload: bytes,
) -> tuple[int, int, str, int | None, str, list[bytes | None], list[int]]: ...
def decode_protocol_envelope_py(payload: bytes) -> tuple[int, Any]: ...


class MerkleProof:
    @property
    def leaf_index(self) -> int: ...
    @property
    def siblings(self) -> List[bytes]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "MerkleProof": ...


class EncodedShard:
    def __init__(self, index: int, data: bytes, proof: MerkleProof) -> None: ...
    @property
    def index(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    @property
    def proof(self) -> MerkleProof: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "EncodedShard": ...


class MerkleResult:
    @property
    def root(self) -> bytes: ...
    @property
    def shards(self) -> List[bytes]: ...
    @property
    def proofs(self) -> List[MerkleProof]: ...
    def shard(self, i: int) -> bytes: ...
    def proof(self, i: int) -> MerkleProof: ...
    def encoded_shard(self, i: int) -> EncodedShard: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "MerkleResult": ...


def merkle_encode(data: bytes, k: int, n: int) -> MerkleResult: ...
def merkle_verify(shard: bytes, proof: MerkleProof, root: bytes) -> bool: ...
def merkle_decode(
    available: List[EncodedShard],
    root: bytes,
    k: int,
    n: int,
) -> bytes: ...
