from typing import List

"""
Type stubs for honey_native Rust module.
Provides threshold signatures and Merkle-tree helpers used by the
Rust ACS bridge (honey-node).  Protocol-envelope codec and crypto-param
generation have been retired from this public API; those functions now live
inside honey-node/src/acs/python.rs as private Rust helpers.
"""

class SigPublicKey:
    @property
    def players(self) -> int: ...
    @property
    def threshold(self) -> int: ...
    def verify_share(self, player_id: int, sig_bytes: bytes, msg: bytes) -> bool: ...
    def verify_combined(self, sig_bytes: bytes, msg: bytes) -> bool: ...
    def verify_share_batch(self, shares: list[tuple[int, bytes, bytes]]) -> list[bool]: ...
    def combine_shares(self, shares: list[tuple[int, bytes]], msg: bytes) -> bytes: ...
    def combine_trusted_shares(self, shares: list[tuple[int, bytes]], msg: bytes) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "SigPublicKey": ...

class SigPrivateShare:
    @property
    def player_id(self) -> int: ...
    def sign(self, msg: bytes) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "SigPrivateShare": ...

def sig_generate(players: int, threshold: int) -> tuple[SigPublicKey, list[SigPrivateShare]]: ...
def ecdsa_generate_keys(players: int) -> tuple[list[bytes], list[bytes]]: ...
def ecdsa_public_key_from_private(priv_key: bytes) -> bytes: ...
def ecdsa_sign(priv_key: bytes, msg: bytes) -> bytes: ...
def ecdsa_verify(pub_key: bytes, msg: bytes, sig_bytes: bytes) -> bool: ...
def ecdsa_verify_threshold_sigs(
    pub_keys: list[bytes], digest: bytes, sigmas: list[tuple[int, bytes]], threshold: int
) -> bool: ...

class MerkleProof:
    @property
    def leaf_index(self) -> int: ...
    @property
    def siblings(self) -> List[bytes]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "MerkleProof": ...

class EncodedShard:
    def __init__(self, index: int, data: bytes, proof: MerkleProof) -> None: ...
    @property
    def index(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    @property
    def proof(self) -> MerkleProof: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "EncodedShard": ...

class MerkleResult:
    @property
    def root(self) -> bytes: ...
    @property
    def shards(self) -> List[bytes]: ...
    @property
    def proofs(self) -> List[MerkleProof]: ...
    def shard(self, i: int) -> bytes: ...
    def proof(self, i: int) -> MerkleProof: ...
    def encoded_shard(self, i: int) -> EncodedShard: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(b: bytes) -> "MerkleResult": ...

def merkle_encode(data: bytes, k: int, n: int) -> MerkleResult: ...
def merkle_verify(shard: bytes, proof: MerkleProof, root: bytes) -> bool: ...
def merkle_decode(
    available: List[EncodedShard],
    root: bytes,
    k: int,
    n: int,
) -> bytes: ...
def merkle_decode_dicts(
    stripes: dict[int, bytes],
    proofs: dict[int, bytes],
    root: bytes,
    k: int,
    n: int,
) -> bytes: ...
